const ADD_SITE = 'ADD_SITE';
const DELETE_SITE = 'DELETE_SITE';
const EDIT_SITE = 'EDIT_SITE';
const ADD_HEADER = 'ADD_HEADER';
const DELETE_HEADER = 'DELETE_HEADER';
const EDIT_HEADER = 'EDIT_HEADER';
const ADD_RULE = 'ADD_RULE';
const DELETE_RULE = 'DELTE_RULE';
const EDIT_RULE = 'EDIT_RULE';

export default {
  ADD_SITE,
  DELETE_SITE,
  EDIT_SITE,
  ADD_HEADER,
  DELETE_HEADER,
  EDIT_HEADER,
  ADD_RULE,
  DELETE_RULE,
  EDIT_RULE,
}
